config/routes.rb
Rails.application.routes.draw do
  resources :topics, only: [:index, :show]

  devise_for :users, path:  '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'registration'}
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  get 'angular-items', to: 'portfolios#angular'

  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  root to: 'pages#home'
  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  resources :blogs do
    member do
      get :toggle_status
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/blog.rb
class Blog < ApplicationRecord
  enum status: { draft: 0, published: 1}
  extend FriendlyId
  friendly_id :title, use: :slugged

  validates_presence_of :title, :body
  belongs_to :topic

  def self.recent
    order('created_at DESC')
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy, :toggle_status ]
  before_action :get_topics, only: [:edit, :update, :new]
  before_action :set_sidebar_topics, except: [:update, :create, :destroy, :toggle_status]
  layout 'blog'
  access all: [:show, :index], user: {except: [:destroy, :new, :create, :update, :edit, :toggle_status]}, site_admin: :all

  # GET /blogs
  # GET /blogs.json
  def index
    if logged_in?(:site_admin)
      @blogs = Blog.recent.page(params[:page]).per(5)
    else
      @blogs = Blog.published.recent.page(params[:page]).per(5)
    end
    @page_title = "My Portfolio Blog"
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
    @page_title = @blog.title
    @seo_keywords = @blog.body
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, success: 'Blog was created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, success: 'Blog was updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, success: 'Blog was deleted.' }
      format.json { head :no_content }
    end
  end

  def toggle_status
    if @blog.draft?
      @blog.published!
    else
      @blog.draft!
    end
    redirect_to blogs_url, success: "Blog status has been updated to #{@blog.status}"
  end

  private
    def get_topics
      @topics = Topic.all
    end

    def set_blog
      @blog = Blog.friendly.find(params[:id])
      unless logged_in?(:site_admin) || @blog.published?
        redirect_to(blogs_path, warning: 'You are not authorzed to access that page')
      end
    end

    def set_sidebar_topics
      @side_bar_topics = Topic.with_blogs
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :body, :topic_id, :status)
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def blog_status_style(blog)
    'opacity: 0.5; color: red' if blog.draft?
  end
end

app/views/blogs/_admin_actions.html.erb
<% if logged_in?(:site_admin) %>
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb blogcrumb">
      <%= link_to fa_icon('file-text'), toggle_status_blog_path(blog), title: blog.status, style: blog_status_style(blog) %>
      <%= link_to fa_icon('pencil-square-o'), edit_blog_path(blog) %>
      <%= link_to fa_icon('trash'), blog, method: :delete, data: { confirm: 'Are you sure?' } %>
    </ol>
  </nav>
<% end %>



app/views/blogs/_blog.html.erb
<div class="blog-post">
  <h3 class="blog-post-title"><%= link_to blog.title.upcase, blog %></h3>
  <p class="blog-post-meta"><%= distance_of_time_in_words(blog.created_at, Time.now) %> ago</p>
  <p>
    <%= blog.body %>
  </p>
  <%= render 'admin_actions', blog: blog %>
</div>

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true) do |form| %>
  <% if blog.errors.any? %>
    <%= alert_generator blog.errors.full_messages, :error %>
  <% end %>
  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :topic_id %>
    <%= form.collection_select(:topic_id, @topics, :id, :title, {prompt: true}, {class: 'form-control'}) %>
  </div>

  <div class="form-group">
    <%= form.radio_button :status, 'draft' %>
    <%= form.label :status, 'Draft' %>
    <%= form.radio_button :status, 'published' %>
    <%= form.label :status, 'Published' %>
  </div>

  <div class="form-group">
    <%= form.label :body %>
    <%= form.text_area :body, class: 'form-control', rows: 15 %>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<div class="col-md-8 blog-main">
  <h1>Editing Blog</h1>

  <%= render 'form', blog: @blog %>

  <%= link_to 'Show', @blog %> |
  <%= link_to 'Back', blogs_path %>
</div>

app/views/blogs/index.html.erb
<div class="col-md-8 blog-main">
  <%= paginate @blogs %>

  <%= render @blogs %>

  <%= paginate @blogs %>

</div> <!-- /.blog-main -->

app/views/blogs/new.html.erb
<div class="col-md-8 blog-main">
  <h1>New Blog</h1>

  <%= render 'form', blog: @blog %>

  <%= link_to 'Back', blogs_path %>
</div>

app/views/blogs/show.html.erb
<div class="col-md-8 blog-main">
  <h2> <%= @blog.title %></h2>

  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <%= tag.li link_to('Home', root_path), class: 'breadcrumb-item' %>
      <%= tag.li link_to(@blog.topic.title, topic_path(@blog.topic)), class: 'breadcrumb-item' %>
      <%= tag.li @blog.title , {class: 'breadcrumb-item active', 'aria-current': "page"}%>
      <% if logged_in?(:site_admin) %>
        <%= tag.li link_to(fa_icon('pencil-square-o'), edit_blog_path(@blog)), class: 'ml-auto' %>
        <%= tag.li link_to(fa_icon('trash'), @blog, method: :delete,
                           data: {confirm: 'Are you sure you want to delete this post?'}), class: 'ml-1' %>
      <% end %>

    </ol>
  </nav>


  <%= tag.h3 @blog.topic.title %>
  <%= link_to 'Edit', edit_blog_path(@blog) if logged_in?(:site_admin) %>
  <p>
    <%= @blog.body %>
  </p>
</div> <!-- /.blog-main -->