config/routes.rb
Rails.application.routes.draw do
  resources :topics, only: [:index, :show]

  devise_for :users, path:  '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'registration'}
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  get 'angular-items', to: 'portfolios#angular'

  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  root to: 'pages#home'
  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  resources :blogs do
    member do
      get :toggle_status
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  has_many :technologies
  accepts_nested_attributes_for :technologies,
                                allow_destroy: true,
                                reject_if: lambda { |attrs| attrs['name'].blank? }
  include Placeholder
  validates_presence_of :title, :body, :main_image, :thumb_image

  def self.angular
    where(subtitle: 'Angular')
  end

  def self.by_position
    order('position ASC')
  end

  scope :ruby_on_rails_portfolio_items, -> { where(subtitle: 'Ruby on Rails')}

  after_initialize :set_defaults

  def set_defaults
    self.main_image ||= Placeholder.image_generator(height: '600', width: '400')
    self.thumb_image ||= Placeholder.image_generator(height: '350', width: '200')
  end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  layout 'portfolio'
  access all: [:show, :index, :angular], user: {except: [:destroy, :new, :create, :update, :edit, :sort]}, site_admin: :all

  before_action :set_portfolio, only: [:show, :edit, :update, :destroy]
  before_action :hide_masthead, only: [:new, :edit]

  def index
    @portfolio_items = Portfolio.by_position
  end

  def sort
    params[:order].each do |key, value|
      Portfolio.find(value[:id]).update(position: value[:position])
    end
    render body: nil
  end

  def new
    @portfolio_item = Portfolio.new
  end

  def angular
    @angular_portfolio_items = Portfolio.angular
  end

  def create
    @portfolio_item = Portfolio.new(portfolio_params)

    respond_to do |format|
      if @portfolio_item.save
        format.html { redirect_to portfolios_path, success: 'Portfolio was created.' }
      else
        format.html { render :new }
      end
    end
  end

  def edit; end

  def update
    respond_to do |format|
      if @portfolio_item.update(portfolio_params)
        format.html { redirect_to portfolios_path, success: 'Portfolio was updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def show; end

  def destroy
    @portfolio_item.destroy
    respond_to do |format|
      format.html {redirect_to portfolios_path, success: 'Portfolio was removed'}
    end
  end

  private

  def hide_masthead
    @hide_masthead = true
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_portfolio
    @portfolio_item = Portfolio.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def portfolio_params
    params.require(:portfolio).permit(:title,
                                      :subtitle,
                                      :body,
                                      technologies_attributes: [:id, :name, :_destroy]
    )
  end
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/portfolios/_form.html.erb
<%= form_with(model: portfolio_item, local: true) do |form| %>
  <% if portfolio_item.errors.any? %>
    <%= alert_generator portfolio_item.errors.full_messages, :error %>
  <% end %>

  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= form.label :title %>
        <%= form.text_field :title, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label :subtitle %>
        <%= form.text_area :subtitle, class: 'form-control' %>
      </div>
    </div>
    <div class="col-md-6">
      <div class="form-group">
        <%= form.label :body %>
        <%= form.text_area :body, class: 'form-control', rows: 13 %>
      </div>
    </div>

  </div>

  <hr>
  <div class="container col-md-4 ml-3">
    <h2>Technologies Used</h2>
    <%= form.fields_for :technologies do |tf| %>
      <%= render 'technology_fields', f: tf %>
    <% end %>
    <div class="div">
      <%= link_to_add_association 'Add Technology', form, :technologies %>
    </div>
  </div>


  <div class="actions">
    <%= form.submit class: 'btn btn-primary btn-block' %>
  </div>
<% end %>

app/views/portfolios/_portfolio_item.html.erb
<div class="col-md-4" data-id="<%= portfolio_item.id %>">
  <div class="card mb-4 shadow-sm">
    <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: Thumbnail"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"></rect><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>
    <div class="card-body">
      <p class="card-text"><%= link_to portfolio_item.title, portfolio_show_path(portfolio_item) %></p>
      <div class="d-flex justify-content-between align-items-center">
          <small class="text-muted"><%= portfolio_item.subtitle %></small>
      </div>
    </div>
  </div>
</div>


app/views/portfolios/_technology_fields.html.erb
<div class="form-group nested-fields">
  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>
  <%= link_to_remove_association 'Remove Technology', f %>
</div>

app/views/portfolios/angular.html.erb
<h1>Angular Portfolio Items</h1>

<%= link_to 'Create new portfolio', new_portfolio_path if logged_in?(:site_admin)%>
<% @angular_portfolio_items.each do |item|%>
  <p><%= link_to item.title, portfolio_show_path(item) %></p>
  <p><%= item.subtitle %></p>
  <p><%= item.body %></p>
  <p><%= image_tag item.thumb_image if item.thumb_image %></p>
  <%= link_to 'Edit', edit_portfolio_path(item) if logged_in?(:site_admin) %> |
  <%= link_to 'Delete', portfolio_path(item), method: :delete, data: { confirm: 'Are you sure?' } if logged_in?(:site_admin)%>
<% end %>

app/views/portfolios/edit.html.erb
<div class="container">
  <%= tag.h1 'Edit Portfolio Item' %>


  <%= render 'form', portfolio_item: @portfolio_item %>
</div>

app/views/portfolios/index.html.erb
<main role="main">
  <div class="album py-5 bg-light">
    <div class="container">
      <div class="row <%= "sortable" if logged_in?(:site_admin) %>">
        <%= render partial: 'portfolio_item', collection: @portfolio_items%>
      </div>
    </div>
  </div>

</main>



<%= link_to 'Create new portfolio', new_portfolio_path if logged_in?(:site_admin)%>


app/views/portfolios/new.html.erb
<div class="container">
  <%= tag.h1 'Create Portfolio Item' %>
  <%= render 'form', portfolio_item: @portfolio_item %>
</div>


app/views/portfolios/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-7">
      <%= image_tag @portfolio_item.main_image if @portfolio_item.main_image %>

    </div>
    <div class="col-md-5">
      <h1><%= @portfolio_item.title %></h1>
      <em><%= @portfolio_item.subtitle %></em>
      <%= link_to(' (Edit)', edit_portfolio_path(@portfolio_item.id)) if logged_in?(:site_admin) %>
      <p><%= @portfolio_item.body %></p>

      <h2>Technologies Used</h2>
      <% @portfolio_item.technologies.each do |t| %>
        <p><%= t.name %></p>
      <% end %>
    </div>
  </div>
</div>

