config/routes.rb
Rails.application.routes.draw do
  resources :topics, only: [:index, :show]

  devise_for :users, path:  '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'registration'}
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  get 'angular-items', to: 'portfolios#angular'

  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  root to: 'pages#home'
  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  resources :blogs do
    member do
      get :toggle_status
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_application_footer.html.erb
<footer class="mastfoot mt-auto">
  <div class="inner">
    <p><%= copywrite_generator %></p>
  </div>
</footer>

app/views/shared/_application_nav.html.erb
<header class="masthead mb-auto">
  <div class="inner">
    <h3 class="masthead-brand">Marcos Galigarcia</h3>
    <nav class="nav nav-masthead justify-content-center">
      <%= nav_helper 'span', 'nav-link mx-3'%>

      <%= login_helper 'nav-link' %>

    </nav>
  </div>
</header>

app/views/shared/_blog_footer.html.erb
<footer class="blog-footer">
  <p>
    <<%= copywrite_generator %>
  </p>
  <p>
    <a href="#">Back to top</a>
</p>
</footer>

app/views/shared/_blog_masthead.html.erb
<header class="blog-header py-3">
  <div class="row flex-nowrap justify-content-between align-items-center">
    <div class="col-4 pt-1">
      <a class="text-muted" href="#">Subscribe</a>
      <span>
        <%= link_to 'Write a New Blog', new_blog_path if logged_in?(:site_admin)%>
      </span>
      <span>
        <%= link_to 'Topics', topics_path%>
      </span>

    </div>
    <div class="col-4 text-center">
      <a class="blog-header-logo text-dark" href="#">My Blog</a>
    </div>
    <div class="col-4 d-flex justify-content-end align-items-center">
      <a class="text-muted" href="#">
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="mx-3" role="img" viewBox="0 0 24 24" focusable="false"><title>Search</title><circle cx="10.5" cy="10.5" r="7.5"></circle><path d="M21 21l-5.2-5.2"></path></svg>
      </a>
      <a class="btn btn-sm btn-outline-secondary" href="#">Sign up</a>
    </div>
  </div>
</header>

app/views/shared/_blog_nav.html.erb
<div class="nav-scroller py-1 mb-2">
  <nav class="nav d-flex justify-content-between">
    <%= nav_helper 'span', 'p-2 text-muted' %>
    <%= tag.span(login_helper "p-2 text-muted") %>
  </nav>
</div>

app/views/shared/_blog_sidebar.html.erb
<aside class="col-md-4 blog-sidebar">
  <div class="p-4 mb-3 bg-light rounded">
    <h4 class="font-italic">About</h4>
    <p class="mb-0">Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
  </div>

  <div class="p-4">
    <h4>Topics</h4>
    <% @side_bar_topics.each do |topic| %>
      <%= tag.p link_to topic.title, topic_path(topic) %>
    <% end %>
  </div>

  <div class="p-4">
    <h4 class="font-italic">Elsewhere</h4>
    <ol class="list-unstyled">
      <li></li>
      <li><%= link_to (fa_icon "github 2x"), "#" %></li>
      <li><%= link_to (fa_icon "instagram 2x"), "#" %></li>
      <li><%= link_to (fa_icon "twitter 2x"), "#" %></li>
      <li><%= link_to (fa_icon "facebook 2x"), "#" %></li>
    </ol>
  </div>
</aside>

app/views/shared/_portfolio_footer.html.erb
<footer class="text-muted">
  <div class="container">
    <p class="float-right">
      <%= link_to 'View All Portfolio Items', portfolios_path %> / 
      <a href="#">Back to top</a>
    </p>
    <p>
      <%= copywrite_generator %>
    </p>
  </div>
</footer>

app/views/shared/_portfolio_masthead.html.erb
<section class="jumbotron text-center">
  <div class="container">
    <h1 class="jumbotron-heading">My Portfolio</h1>
    <p class="lead text-muted">Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don’t simply skip over it entirely.</p>
    <p>
      <%= link_to 'Find out more about me', about_me_path, class: "btn btn-primary my-2" %>
      <%= link_to 'My Blog', blogs_path, class: "btn btn-secondary my-2" %>
    </p>
  </div>
</section>

app/views/shared/_portfolio_nav.html.erb
<header>
  <div class="bg-dark collapse" id="navbarHeader" style="">
    <div class="container">
      <div class="row">
        <div class="col-sm-8 col-md-7 py-4">
          <h4 class="text-white">About</h4>
          <p class="text-muted">Add some information about the album below, the author, or any other background context. Make it a few sentences long so folks can pick up some informative tidbits. Then, link them off to some social networking sites or contact information.</p>
        </div>
        <div class="col-sm-4 offset-md-1 py-4">
          <h4 class="text-white">Explore</h4>
          <ul class="list-unstyled">
            <%= nav_helper 'li', 'text-white' %>
            <li><%= login_helper "text-white" %></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="navbar navbar-dark bg-dark shadow-sm">
    <div class="container d-flex justify-content-between">
      <a href="#" class="navbar-brand d-flex align-items-center">
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="mr-2" viewBox="0 0 24 24" focusable="false"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"></path><circle cx="12" cy="13" r="4"></circle></svg>
        <strong>Marcos</strong>
      </a>
      <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </div>
</header>